<?php

namespace App\DataFixtures;


class AppProvider
{
    private $planets = [
        [
            'title' =>  'Manaan',
            'destination' =>  'Manaan',
            'description' => 'Manaan est une planète océanique de l\'univers de Star Wars, située dans la Bordure Médiane. Elle est principalement connue pour être le monde natal de la race des Selkaths, des êtres amphibiens à la peau visqueuse et aux grands yeux adaptés à la vie sous-marine. La planète est presque entièrement recouverte d\'eau, avec seulement quelques îles et archipels émergeant de la surface. Les villes Selkath sont construites sous l\'eau, dans de grandes bulles d\'air, et sont reliées entre elles par un réseau de tunnels sous-marins. Manaan est également célèbre pour son exportation d\'un précieux produit, le kolto, un baume guérisseur aux propriétés régénératrices exceptionnelles. Le kolto est produit par des créatures marines géantes appelées Opee, et sa récolte est une industrie majeure sur la planète. La planète est neutre dans les conflits galactiques, et les Selkaths sont réputés pour leur sagesse et leur diplomatie. Cependant, pendant la Guerre Civile des Jedi, la planète a été brièvement envahie par les forces Sith, qui cherchaient à prendre le contrôle de la production de kolto.',
            'picture' => 'https://th.bing.com/th/id/OIG3.c3jOW41Lzf3Sn6NPhhFo?pid=ImgGn',
            'departure' => '22 / 04 / 2025',
            'duration' => 16,
            'passenger' => 8,
            'price' => 300000,
        ],
        [
            'title' => 'Tatooine',
            'destination' => 'Tatooine',
            'description' => 'Une planète désertique située dans la Bordure Extérieure de la galaxie, célèbre pour ses deux soleils qui brûlent implacablement dans un ciel sans nuages. Ses vastes étendues de sable, marquées par des dunes immenses et des canyons rocailleux, en font un monde impitoyable et inhospitalier pour ceux qui y vivent. Les habitants de Tatooine, comme les Jawas et les Tusken Raiders, ont développé des modes de vie adaptés à ce climat aride et difficile. Les villes telles que Mos Eisley et Mos Espa, bien que rudimentaires, sont des centres d\'activité où les marchands, les contrebandiers et les chasseurs de primes se croisent régulièrement. Malgré son isolement et son environnement hostile, Tatooine est souvent le théâtre d\'événements clés dans la saga Star Wars. C\'est ici que Luke Skywalker a grandi sous la tutelle de son oncle Owen Lars, avant de partir à l\'aventure et de devenir un Jedi.',
            'picture' => 'https://th.bing.com/th/id/OIG3.YStffe54sAOCHLz7q8a.?pid=ImgGn',
            'departure' => '11 / 11 / 2025',
            'duration' => 7,
            'passenger' => 6,
            'price' => 35000, 
        ],
        [
            'title' => 'Coruscant',
            'destination' => 'Coruscant',
            'description' => 'Coruscant, souvent surnommée la "Perle de la Galaxie", est une planète emblématique située au cœur de la galaxie Star Wars. Entièrement urbanisée, elle est recouverte d\'un immense tapis de gratte-ciel, de tours étincelantes et de vastes plateformes urbaines qui s\'étendent à perte de vue. En tant que siège du pouvoir de la République Galactique et plus tard de l\'Empire Galactique, Coruscant est le centre politique, économique et culturel de la galaxie. Ses immenses tours abritent les institutions gouvernementales telles que le Sénat Galactique, le Palais Impérial et les bureaux des différentes factions politiques et commerciales. Coruscant est également un carrefour cosmopolite où se croisent des milliards d\'espèces venues de tous les coins de la galaxie. Ses niveaux inférieurs, souvent plongés dans l\'obscurité et la criminalité, contrastent avec les quartiers plus huppés et sécurisés des hauteurs de la ville. Dans ses rues animées, on trouve une multitude de commerces, de marchés exotiques, de cantinas et de lieux de divertissement.',
            'picture' => 'https://images.nightcafe.studio/jobs/IJxJNSNnaMoccZxph2zW/IJxJNSNnaMoccZxph2zW--1--4pneq.jpg?tr=w-1600,c-at_max',
            'departure' => '12 / 05 / 2025',
            'duration' => 15,
            'passenger' => 6,
            'price' => 85000, 
        ],
        [
            'title' => 'Hoth',
            'destination' => 'Hoth',
            'description' => 'Une planète glacée située dans les régions les plus reculées de la galaxie Star Wars, est un monde hostile et impitoyable. Sa surface est entièrement recouverte de vastes étendues de glace et de neige, balayées par des tempêtes féroces et des vents glacials. Le paysage désolé de Hoth est ponctué de crêtes rocheuses, de crevasses profondes et de formations de glace spectaculaires. Les températures extrêmement basses rendent la vie difficile, même pour les espèces les plus adaptées au froid. Seuls les organismes les plus résistants, tels que les Wampas et les Tauntauns, parviennent à survivre dans ce climat hostile. Malgré son isolement et son environnement hostile, Hoth est devenu célèbre dans toute la galaxie en raison de sa connexion avec l\'Alliance Rebelle. C\'est sur cette planète glacée que l\'Alliance a établi sa base secrète, dissimulée sous la surface gelée pour échapper à la détection de l\'Empire Galactique. Cette base devient un point crucial dans la lutte de l\'Alliance contre l\'Empire, servant de refuge aux rebelles et de centre stratégique pour la planification de leurs opérations. La bataille de Hoth, l\'un des moments les plus mémorables de la saga Star Wars, a lieu sur cette planète inhospitalière. L\'Empire lance une attaque massive contre la base rebelle, déclenchant une bataille épique entre les forces impériales et les courageux combattants de l\'Alliance. Les imposants marcheurs impériaux avancent à travers les étendues glacées, tandis que les pilotes rebelles se battent héroïquement pour défendre leur base.',
            'picture' => 'https://th.bing.com/th/id/OIG3.X3F4QVYuAfaSQPlDkLwO?pid=ImgGn',
            'departure' => '04 / 01 / 2025',
            'duration' => 7,
            'passenger' => 6,
            'price' => 25000, 
        ],
        [
            'title' => 'Naboo',
            'destination' => 'Naboo',
            'description' => 'une planète emblématique de la galaxie Star Wars, est un monde d\'une beauté remarquable et d\'une richesse culturelle profonde. Située dans la région des Mondes du Noyau, Naboo est réputée pour ses paysages idylliques, ses vastes étendues de prairies verdoyantes, ses lacs sereins et ses palais majestueux. La planète est habitée par deux principales espèces intelligentes : les humains, qui résident principalement dans les cités élégantes et sophistiquées, et les Gungans, qui vivent dans les profondeurs des océans de Naboo. Malgré leurs différences culturelles et leur histoire tumultueuse, les deux peuples coexistent en harmonie sur cette planète paisible. Naboo est célèbre pour ses sites historiques et architecturaux remarquables, tels que le Palais de Theed, une magnifique résidence royale qui sert de siège au gouvernement de la planète. Les villes de Naboo sont caractérisées par leur architecture élégante et leurs jardins luxuriants, créant une atmosphère de grâce et de raffinement. Outre sa beauté naturelle et son patrimoine culturel, Naboo joue un rôle important dans l\'histoire de la galaxie en tant que foyer de l\'Alliance Rebelle naissante. C\'est sur cette planète que la reine Padmé Amidala, célèbre pour son rôle dans la lutte contre l\'Empire Galactique, a commencé sa carrière politique.',
            'picture' => 'https://th.bing.com/th/id/OIG1._tE.D4vzgFnwLnj.cWGh?pid=ImgGn',
            'departure' => '14 / 02 / 2025',
            'duration' => 7,
            'passenger' => 6,
            'price' => 100000,
        ],
        [
            'title' => 'Endor',
            'destination' => 'Endor',
            'description' => 'Endor est une lune forestière située dans la Bordure Extérieure de la galaxie Star Wars. Elle est surtout connue pour être le lieu où se déroule la bataille finale entre l\'Alliance Rebelle et l\'Empire Galactique dans le film "Le Retour du Jedi". Caractérisée par ses vastes forêts denses, ses canyons escarpés et ses nombreux marécages, Endor abrite une biodiversité riche et variée, y compris sa population indigène, les Ewoks. Les Ewoks sont des créatures petites et pelucheuses qui habitent les arbres de la lune forestière. Bien qu\'ils aient une apparence mignonne, les Ewoks sont des guerriers redoutables qui ont utilisé leur connaissance de la forêt et leur ingéniosité pour combattre l\'Empire lors de la bataille de Endor. Leur aide inattendue a été cruciale pour la victoire de l\'Alliance Rebelle. Outre sa faune unique, Endor possède également des paysages spectaculaires, notamment ses immenses arbres géants appelés arbres-maisons, qui servent de domicile aux Ewoks. Ces arbres sont reliés par des passerelles en bois tressé, créant un réseau complexe de villages dans les cimes des arbres. Endor est également le site d\'une base lunaire impériale, où l\'Empire a établi un avant-poste pour protéger la nouvelle station spatiale de combat, l\'Étoile de la Mort II. La destruction de cette station, lors de la bataille de Endor, a été un coup décisif porté à l\'Empire et a contribué à la chute de l\'Empereur Palpatine.',
            'picture' => 'https://th.bing.com/th/id/OIG1.Hc4nJ0pNbQ2xBJONHJOS?w=1024&h=1024&rs=1&pid=ImgDetMain',
            'departure' => '20 / 03 / 2025',
            'duration' => 15,
            'passenger' => 6,
            'price' => 90000,
        ],
        [
            'title' => 'Bespin',
            'destination' => 'Bespin',
            'description' => 'Bespin est une planète gazeuse située dans la Bordure Extérieure de la galaxie Star Wars. Connu pour ses vastes nuages et son atmosphère respirable, Bespin abrite l\'une des cités les plus emblématiques de la saga, Cloud City. Cloud City flotte au-dessus des couches denses de nuages de Bespin, suspendue dans les airs par d\'immenses plates-formes de repulsion et de gravité artificielles. La cité est un centre d\'activité économique et politique, dirigée par Lando Calrissian, un ancien contrebandier devenu administrateur de la ville. Bien que Bespin soit principalement un site industriel et minier, ses vastes étendues de nuages cachent également de riches gisements de tibanna, un gaz précieux utilisé dans la fabrication de carburant et d\'armes énergétiques. C\'est cette ressource qui a attiré l\'intérêt de la Corporation Minérale de Bespin et qui a conduit à la création de Cloud City comme centre de traitement et de raffinage du tibanna. En plus de son importance économique, Bespin est également un lieu de rencontre pour les voyageurs de toute la galaxie. La cité flottante offre des divertissements, des jeux de hasard et des opportunités commerciales pour ceux qui cherchent à faire des affaires ou à échapper à leurs ennuis.',
            'picture' => 'https://th.bing.com/th/id/OIG1.HyLEZNpEjHJBgKyTe6pl?pid=ImgGn',
            'departure' => '14 / 05 / 2025',
            'duration' => 15,
            'passenger' => 6,
            'price' => 80000,
        ],
        [
            'title' => 'Kashyyyk',
            'destination' => 'Kashyyyk',
            'description' => 'Kashyyyk est une planète forestière située dans la région de la Bordure Extérieure de la galaxie Star Wars. Elle est célèbre pour être le monde natal des Wookiees, une espèce de grands humanoïdes recouverts de poils, connus pour leur force physique et leur bravoure. Les vastes jungles de Kashyyyk abritent une faune et une flore variées, avec d\'immenses arbres géants appelés "arbres Wroshyr" qui dominent le paysage. Ces arbres servent de foyer et de lieu de vie pour les Wookiees, qui ont développé des sociétés tribales complexes au sein de leurs branches massives. En plus d\'être le foyer des Wookiees, Kashyyyk est également connu pour sa riche biodiversité, avec une variété d\'espèces animales et végétales uniques. Cependant, la planète est également le théâtre de conflits et d\'intrigues, en particulier pendant les périodes de guerre dans la galaxie. Pendant la Guerre des Clones, Kashyyyk est devenue un champ de bataille entre les forces de la République Galactique et l\'armée droïde de la Confédération des Systèmes Indépendants. Les Wookiees se sont battus avec courage pour défendre leur planète contre l\'invasion, et leur résistance héroïque est devenue légendaire dans toute la galaxie. Malgré les défis et les menaces qui pèsent sur elle, Kashyyyk reste un symbole de la force et de la résilience du peuple Wookiee. Les vastes jungles de la planète offrent un refuge pour ceux qui cherchent à échapper à l\'oppression et à la tyrannie, et sa beauté naturelle continue d\'inspirer les voyageurs et les aventuriers à travers la galaxie.',
            'picture' => 'https://th.bing.com/th/id/OIG2.xzORDYXj33QJXT3dBjI.?pid=ImgGn',
            'departure' => '10 / 10 / 2025',
            'duration' => 15,
            'passenger' => 6,
            'price' => 30000,
        ],
        [
            'title' =>  'Geonosis',
            'destination' =>  'Geonosis',
            'description' => 'Geonosis est une planète aride et rocailleuse située dans la Bordure Extérieure de la galaxie Star Wars. Elle est principalement connue pour ses vastes déserts et ses formations rocheuses uniques. La surface de Geonosis est parsemée de cratères, de canyons et de formations géologiques spectaculaires, créant un paysage désolé et inhospitalier. Cette planète désertique abrite également une faune et une flore adaptées à son environnement extrême, comprenant des créatures telles que les reeks et les nexu, ainsi que des plantes résistantes capables de survivre dans des conditions arides. Cependant, ce qui rend Geonosis particulièrement célèbre dans l\'histoire de la galaxie, ce sont ses installations industrielles et ses liens avec la Confédération des Systèmes Indépendants (CSI) pendant les Guerres des Clones. En tant que l\'un des principaux mondes soutenant le mouvement séparatiste, Geonosis est devenu un bastion de l\'armée droïde et un centre de production d\'armes et de matériel militaire. La planète est également le théâtre de la bataille de Geonosis, l\'un des premiers affrontements majeurs de la Guerre des Clones. Cette bataille a vu s\'affronter les forces de la République Galactique et de la Confédération des Systèmes Indépendants, marquant le début d\'un conflit dévastateur qui allait embraser la galaxie pendant de nombreuses années. Malgré sa réputation de monde hostile et dangereux, Geonosis continue d\'exercer une fascination pour de nombreux habitants de la galaxie, attirant les aventuriers, les chercheurs de trésors et les explorateurs à la recherche de connaissances ou de richesses cachées dans ses déserts inhospitaliers.',
            'picture' => 'https://th.bing.com/th/id/OIG2.whPQ53feIR.jWLqVzoq3?pid=ImgGn',
            'departure' => '01 / 08 / 2025',
            'duration' => 7,
            'passenger' => 6,
            'price' => 25000,
        ],
        [
            'title' =>  'Yavin IV',
            'destination' =>  'Yavin IV',
            'description' => 'Yavin IV est une lune boisée et sauvage située dans la Bordure Extérieure de la galaxie Star Wars. Elle est principalement connue pour avoir abrité la base rebelle utilisée par l\'Alliance rebelle pendant la bataille de Yavin, un événement décisif dans la lutte contre l\'Empire Galactique. La surface de Yavin IV est couverte de vastes forêts luxuriantes et de jungles denses, abritant une variété de faune et de flore exotiques. Parmi les créatures indigènes de la lune, on trouve des prédateurs redoutables tels que les rancors, ainsi que des espèces végétales étranges et mystérieuses. Cependant, ce qui rend Yavin IV particulièrement important dans l\'histoire de la galaxie, c\'est son rôle crucial dans la lutte contre l\'Empire. Après la destruction de la première Étoile de la Mort lors de la bataille de Yavin, l\'Alliance rebelle établit sa base principale sur cette lune isolée, utilisant sa densité forestière et son éloignement pour se cacher des forces impériales. La base rebelle de Yavin IV devient le point de ralliement des forces rebelles, où les pilotes, les soldats et les dirigeants se réunissent pour planifier leurs opérations contre l\'Empire. C\'est également sur Yavin IV que Luke Skywalker reçoit son entraînement de Jedi de la part d\'Obi-Wan Kenobi et de Maître Yoda, devenant ainsi un élément crucial dans la lutte contre le côté obscur de la Force.',
            'picture' => 'https://th.bing.com/th/id/OIG3.laRCyA4IF_8bYTDWWt1a?pid=ImgGn',
            'departure' => '15 / 07 / 2025',
            'duration' => 7,
            'passenger' => 6,
            'price' => 40000,
        ],
        [
            'title' =>  'Jakku',
            'destination' =>  'Jakku',
            'description' => 'Jakku est une planète désertique et aride située dans la Bordure Extérieure de la galaxie Star Wars. Elle est caractérisée par ses vastes étendues de sable et ses paysages stériles, parsemés d\'épaves de vaisseaux spatiaux abandonnés, ce qui en fait un terrain inhospitalier et dangereux pour les voyageurs. Cette planète désolée est souvent considérée comme un symbole de désespoir et de désolation, où les ruines de batailles spatiales passées jonchent le paysage et où les vestiges de la guerre sont omniprésents. Les épaves de vaisseaux éparpillées sur Jakku sont le résultat de batailles historiques et de conflits qui ont secoué la galaxie Star Wars pendant des décennies. Malgré son apparence hostile, Jakku abrite également des communautés de contrebandiers, de ferrailleurs et de chercheurs de trésors, qui exploitent les ressources rares et les technologies abandonnées dissimulées sous le sable. Ces habitants tentent de survivre dans un environnement impitoyable en récupérant et en recyclant les débris des batailles qui ont eu lieu dans l\'espace au-dessus de la planète. Jakku est également connue pour être le lieu de naissance de Rey, l\'héroïne de la trilogie de films Star Wars initiée par "Le Réveil de la Force". C\'est sur cette planète que Rey a été abandonnée dans son enfance et où elle a grandi en tant que ferrailleuse, avant de se lancer dans une aventure qui l\'a conduite à découvrir ses pouvoirs de Force et à jouer un rôle crucial dans la lutte contre le Premier Ordre.',
            'picture' => 'https://th.bing.com/th/id/OIG3.u7iCI.m.G9kgTxoOBynZ?pid=ImgGn',
            'departure' => '10 / 08 / 2025',
            'duration' => 7,
            'passenger' => 6,
            'price' => 20000,
        ],
        [
            'title' =>  'Kamino',
            'destination' =>  'Kamino',
            'description' => 'Kamino est une planète océanique située dans la Bordure Extérieure de la galaxie Star Wars. Elle est entièrement recouverte d\'océans et est souvent enveloppée de tempêtes violentes et de conditions météorologiques tumultueuses. Ce monde aquatique est célèbre pour être le site des installations de clonage les plus avancées de la galaxie. Les principales caractéristiques de Kamino sont ses vastes étendues d\'eau, ses îles émergeant à peine à la surface de l\'océan, et ses structures de haute technologie qui s\'élèvent au-dessus des eaux tumultueuses. Les Kaminoens, l\'espèce indigène de la planète, sont des experts en génétique et en manipulation génétique, et ils ont développé des techniques de clonage très avancées. Kamino est surtout connue pour son rôle crucial dans les Guerres des Clones. Pendant cette période tumultueuse de l\'histoire galactique, la planète est devenue le principal centre de production de clones pour la République Galactique. Sous la supervision des Kaminoens, des millions de clones ont été créés pour servir dans l\'armée de la République, constituant ainsi la célèbre Grande Armée de la République. Les installations de clonage de Kamino sont extrêmement sophistiquées, avec des laboratoires de pointe, des usines de production et des installations d\'entraînement militaire. Les clones produits sur Kamino sont génétiquement modifiés pour posséder des compétences de combat exceptionnelles, ce qui en fait des soldats redoutables sur le champ de bataille.',
            'picture' => 'https://th.bing.com/th/id/OIG2.kPvk6OESt2DO0yESkKgD?pid=ImgGn',
            'departure' => '12 / 12 / 2025',
            'duration' => 15,
            'passenger' => 6,
            'price' => 45000,
        ],
        [
            'title' =>  'Mustafar',
            'destination' =>  'Mustafar',
            'description' => 'Mustafar est une planète volcanique située dans la Bordure Extérieure de la galaxie Star Wars. Elle est caractérisée par ses paysages infernaux, dominés par d\'immenses volcans en éruption, des rivières de lave en fusion et des étendues de roche noire et brûlée. La surface de Mustafar est extrêmement hostile, avec des températures élevées, une atmosphère toxique et des conditions géologiques instables. Les volcans actifs crachent régulièrement des jets de lave en fusion dans les airs, créant un paysage apocalyptique et inhospitalier. Malgré ses dangers, Mustafar a joué un rôle important dans l\'histoire galactique, en particulier pendant la période de la Guerre des Clones. C\'est sur cette planète que se déroule l\'un des moments les plus emblématiques de la saga Star Wars : le duel épique entre Anakin Skywalker, devenu Dark Vador, et son ancien maître Jedi, Obi-Wan Kenobi, dans le film "La Revanche des Sith". Outre son importance symbolique dans l\'histoire de la galaxie, Mustafar est également connue pour abriter des installations minières où des ressources précieuses sont extraites des profondeurs de la planète. Ces ressources, bien que rares, sont extrêmement précieuses sur le marché galactique en raison de leur nature unique et de leur rareté.',
            'picture' => 'https://th.bing.com/th/id/OIG1.mvEkkx8cNgYRsPo2WW7m?pid=ImgGn',
            'departure' => '12 / 12 / 2025',
            'duration' => 15,
            'passenger' => 6,
            'price' => 35000,
        ],
        [
            'title' =>  'Lothal',
            'destination' =>  'Lothal',
            'description' => 'Lothal est une planète située dans la Bordure Extérieure de la galaxie Star Wars. Elle est caractérisée par ses vastes plaines, ses collines ondulantes et ses paysages plutôt paisibles. La planète est principalement connue pour son importante activité minière et agricole. Ses terres fertiles et son climat tempéré en font un endroit idéal pour la culture de diverses cultures et la production de denrées alimentaires. Les habitants de Lothal sont souvent des fermiers et des travailleurs agricoles qui tirent leur subsistance des riches ressources naturelles de la planète. Cependant, Lothal est également le foyer de nombreux rebelles qui luttent contre l\'Empire Galactique. Ils opèrent depuis les régions reculées de la planète, organisant des attaques contre les forces impériales et menant des opérations de sabotage pour affaiblir le contrôle impérial sur la région. Parmi ces rebelles se trouve le jeune Ezra Bridger et l\'équipage du vaisseau Ghost, qui jouent un rôle central dans la lutte contre l\'Empire sur Lothal. En raison de son importance stratégique pour le mouvement rebelle, Lothal est souvent le théâtre de nombreuses batailles et escarmouches entre les forces rebelles et impériales. Les vastes étendues de la planète offrent de nombreuses cachettes et possibilités de guérilla, ce qui en fait un lieu idéal pour mener une résistance contre l\'oppression impériale.',
            'picture' => 'https://th.bing.com/th/id/OIG4.KfxkzIqyrpb5Js_NvK6S?pid=ImgGn',
            'departure' => '05 / 06 / 2025',
            'duration' => 15,
            'passenger' => 6,
            'price' => 70000,
        ],
        [
            'title' =>  'Dagobah',
            'destination' =>  'Dagobah',
            'description' => 'Dagobah est une planète marécageuse et isolée située dans les régions inconnues de la galaxie Star Wars. Elle est surtout connue pour son environnement hostile et sauvage, caractérisé par ses marais sombres et denses, ses jungles impénétrables et ses marécages brumeux. La planète est enveloppée d\'une atmosphère humide et épaisse, créant des conditions de vie difficiles pour toute forme de vie. Ses paysages lugubres et inhospitaliers en font un endroit peu accueillant pour les visiteurs, et seuls ceux qui connaissent bien la région peuvent espérer naviguer avec succès à travers ses nombreux dangers. Dagobah est célèbre dans l\'univers Star Wars comme étant le lieu d\'entraînement de Luke Skywalker sous la tutelle du légendaire Maître Jedi, Yoda. C\'est ici que Luke vient pour développer ses compétences en tant que Jedi et apprendre les voies de la Force. Sous la direction de Yoda, Luke subit un entraînement rigoureux et éprouvant qui le prépare à affronter son destin en tant que chevalier Jedi. Outre son rôle dans la formation de Luke Skywalker, Dagobah est également associée à la Force sombre et mystérieuse qui imprègne la planète. Des visions étranges et des manifestations de la Force peuvent survenir à tout moment, ajoutant à l\'atmosphère mystique et inquiétante de l\'endroit.',
            'picture' => 'https://th.bing.com/th/id/OIG3.Oukk2k1TG0OJ8wteXrir?pid=ImgGn',
            'departure' => '15 / 09 / 2025',
            'duration' => 7,
            'passenger' => 6,
            'price' => 150000,
        ],
        [
            'title' =>  'Scarif',
            'destination' =>  'Scarif',
            'description' => 'Scarif est une planète tropicale située dans la Bordure Extérieure de la galaxie Star Wars. Elle est principalement recouverte d\'océans étendus, avec des plages de sable blanc et des formations rocheuses imposantes. Le climat de Scarif est chaud et humide, avec des températures élevées et des tempêtes tropicales fréquentes. La planète est surtout connue pour abriter une base impériale de recherche et de développement, qui joue un rôle crucial dans la construction de l\'Étoile de la Mort, une super arme redoutable de l\'Empire Galactique. En raison de l\'importance stratégique de la base, Scarif est fortement fortifiée et protégée par les forces impériales. Pendant les événements de Rogue One: A Star Wars Story, un groupe hétéroclite de rebelles lance une audacieuse mission pour voler les plans de l\'Étoile de la Mort sur Scarif. Cette mission est l\'un des moments décisifs de la lutte entre l\'Alliance rebelle et l\'Empire Galactique, et elle se déroule sur les plages idylliques et les installations impériales fortifiées de Scarif. La bataille de Scarif, qui s\'ensuit, est une confrontation épique entre les forces rebelles et impériales, avec des combats terrestres, aériens et spatiaux intenses. Les rebelles parviennent finalement à voler les plans de l\'Étoile de la Mort, mais au prix de nombreux sacrifices. La bataille de Scarif devient ainsi un symbole de la détermination et du courage des rebelles dans leur lutte pour la liberté.',
            'picture' => 'https://th.bing.com/th/id/OIG1.UuDtAg7QCKp.dlAqPUCr?pid=ImgGn',
            'departure' => '10 / 10 / 2025',
            'duration' => 7,
            'passenger' => 6,
            'price' => 200000,
        ],
        [
            'title' =>  'Felucia',
            'destination' =>  'Felucia',
            'description' => 'Felucia est une planète exotique située dans les Régions Inconnues de la galaxie Star Wars. Elle est caractérisée par sa flore luxuriante et ses paysages colorés, mais elle est également connue pour être un lieu dangereux en raison de ses prédateurs mortels et de ses plantes carnivores. Felucia a été le théâtre de nombreuses batailles pendant les Guerres des Clones, et elle est souvent utilisée comme cachette par des criminels et des fugitifs en raison de sa nature sauvage et inhospitalière. Les Jedi ont également été attirés par Felucia en raison de sa Force puissante et de ses liens avec la nature. Le climat de Felucia est tropical et humide, avec des températures élevées et des précipitations abondantes. Les étendues de forêts luxuriantes abritent une grande diversité de créatures, des plus petites aux plus imposantes. Les marais et les jungles de Felucia sont également parsemés de ruines anciennes, témoins d\'une civilisation disparue depuis longtemps. Malgré sa beauté, Felucia est un monde hostile où la vie est souvent menacée par les dangers de la nature et les conflits violents. Sa richesse en ressources naturelles en fait une cible convoitée pour ceux qui cherchent à exploiter ses richesses ou à établir leur pouvoir sur la planète.',
            'picture' => 'https://th.bing.com/th/id/OIG3.ms8cAOWzP0wSA7.pMriH?w=1024&h=1024&rs=1&pid=ImgDetMain',
            'departure' => '10 / 05 / 2025',
            'duration' => 15,
            'passenger' => 6,
            'price' => 95000,
        ],
        [
            'title' =>  'Mandalore',
            'destination' =>  'Mandalore',
            'description' => 'Mandalore est une planète de l\'univers de Star Wars, située dans la Bordure Extérieure. Elle est surtout connue pour être le monde natal de la culture guerrière des Mandaloriens. Mandalore est une planète aride et rocheuse, avec des montagnes, des canyons et des déserts étendus. La planète a une atmosphère respirable, mais elle est souvent balayée par des tempêtes de sable violentes et des vents forts. La culture Mandalorienne est basée sur la guerre et l\'honneur. Les Mandaloriens sont des guerriers redoutables, réputés pour leur armure distinctive en beskar, un métal extrêmement résistant, et pour leur utilisation d\'armes telles que les fusils blaster et les lames vibro. La planète a une longue histoire de conflits et de guerres, et a été le théâtre de nombreuses batailles entre les Mandaloriens et divers ennemis, notamment les Jedi et l\'Empire Galactique. La capitale de Mandalore est Sundari, une ville fortifiée construite sur un plateau surélevé. La ville est entourée de murs épais et est défendue par des guerriers Mandaloriens entraînés. Mandalore a une grande importance symbolique pour les Mandaloriens, qui considèrent la planète comme leur foyer et leur patrie. Bien que de nombreux Mandaloriens aient voyagé dans la galaxie et se soient installés sur d\'autres planètes, Mandalore reste le cœur de leur culture et de leur identité.',
            'picture' => 'https://th.bing.com/th/id/OIG1.Wi0GWKfrkKgl7TP1_FNV?pid=ImgGn',
            'departure' => '25 / 01 / 2024',
            'duration' => 7,
            'passenger' => 6,
            'price' => 75000,
        ],

    ];


    /**
     * Get the value of planets
     */
    public function getPlanets()
    {
        return $this->planets;
    }
}
